name: compile
description: The MobiPkg Compile package, a tool for compiling code to dynamic/static libraries.
version: 0.0.2
repository: https://github.com/MobiPkg/Compile

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lint: ^2.0.1
  test: ^1.21.0
  
dependencies:
  args: ^2.4.0
  logger: ^1.3.0
  path: ^1.8.3
  process_run: ^0.12.5+3
  yaml: ^3.1.1
  yaml_edit: ^2.1.0

executables:
  compile: 