name: compile
description: The MobiPkg Compile package, a tool for compiling code to dynamic/static libraries.
version: 0.0.1-dev.1
repository: https://github.com/MobiPkg/Compile

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
